#!/bin/bash

HOPA_VERSION=1.4V

HOPA_SCRIPT_PATH=$0
EXE_FILE=$(echo $HOPA_SCRIPT_PATH)_exe
HOPA_C=$(echo $HOPA_SCRIPT_PATH).c
PRJ_PATH="$(pwd)"
INC_FILE_NAME="$(pwd)/includes"
SPEC_DIR_NAME="spec"
SPEC_DIR="$PRJ_PATH/$SPEC_DIR_NAME"
HOPA_RES_FILE="hopa_res.conf"
HOPA_DEFINES="-DHOPA_NOT_INCLUDE_FOR_TEST -DHOPA_RES_FILE=$HOPA_RES_FILE"
HOPA_GCC="gcc"
HOPA_LOG_FILE="log"

function print_usage {
    echo "Usage: hopa [options] [files]"
    echo "type: 'hopa --help' for more"
}

function print_version {
    echo "Hopa Test framework $HOPA_VERSION"
}

function print_help {
    echo "Usage: hopa [options] [files]"
    echo "available options:"
    echo "  -h, --help"
    echo "      prints this page"
    echo "  -v, --verbose"
    echo "      be verbose"
    echo "  -V, --version"
    echo "      print program version"
    echo "  init"
    echo "      initialize hopa"
    echo "  update"
    echo "      update from git (git -C hopa/ pull origin master)"
    echo ""
}

function init {
    chmod +x ./hopa/hopa/hopa
    mkdir spec
    if [ $? -ne 0 ]
    then
        exit 1
    else
        echo "make directory spec/"
    fi
}

function update {
    echo "Updating Hopa!..."
    echo
    git -C hopa/ pull origin master
    echo
    echo "done"
}

VERBOSE_MODE=

for key in "$@"
do
case $key in
    --help|-h)
        print_help
        exit 0
        ;;
    --version|-V)
        print_version
        exit 0
        ;;
    --verbose|-v)
        VERBOSE_MODE=1
        ;;
    init)
        init
        exit 0
        ;;
    update)
        update
        exit 0
        ;;
    *)
        INC_FILES="$INC_FILES $key"
        ;;
esac
done

echo "Hopa! $HOPA_VERSION"
echo

if [ ! -d $SPEC_DIR ]
then
    echo
    echo "[Hopa] Error: \`$SPEC_DIR\` directory does not exists."
    echo "Type hopa init"
    exit 1
fi

if [ -f $HOPA_RES_FILE ]
then
    rm $HOPA_RES_FILE
fi
touch $HOPA_RES_FILE
echo "0 0" > $HOPA_RES_FILE

if [ -f $INC_FILE_NAME ]
then
    rm $INC_FILE_NAME
fi
touch $INC_FILE_NAME

if [ -z "$INC_FILES" ]
then
    INC_FILES=`ls -I "*helper*" -I "*tmp*" $SPEC_DIR_NAME/`
fi

for eachfile in $INC_FILES
do
    eachfile="$SPEC_DIR_NAME/$eachfile"
    SRC=""
    echo "#include \"$eachfile\"" > $INC_FILE_NAME
    INC_SRC=$(cat $eachfile | grep -Ei 'source\(\".*"\)' | grep -oEi '\".*\"' | grep -oEi '[^"]*' | tr '\n' ' ')
    if [[ $SRC == *$INC_SRC* ]]; then
        continue
    fi

    if [ ! -z "$INC_SRC" ]
    then
        SRC="$SRC $INC_SRC"
    fi

    COMPILE_CMD="$HOPA_GCC $HOPA_C $SRC -o $EXE_FILE -I$PRJ_PATH $HOPA_DEFINES"

    if [ "$VERBOSE_MODE" ]
    then
        cat $INC_FILE_NAME
        echo $COMPILE_CMD
        $HOPA_GCC -E $HOPA_C $SRC -I$PRJ_PATH -DHOPA_NOT_INCLUDE_FOR_TEST > $HOPA_LOG_FILE
        echo
        $COMPILE_CMD
    else
        $COMPILE_CMD > /dev/null 2>&1
    fi

    if [ $? -ne 0 ]
    then
        echo
        echo "[Hopa] Error: compile error."
        echo "Type 'hopa -v' for verbose mode"
        exit 1
    else
        $EXE_FILE
    fi

    if [ $? -ne 0 ]
    then
        exit 1
    fi
done

read test_num cnt_failure < $HOPA_RES_FILE
printf "\n\e[32m%d examples, %d failures\e[0m\n" $test_num $cnt_failure

if [ -f $INC_FILE_NAME ]
then
    rm $EXE_FILE
    rm $INC_FILE_NAME
    rm $HOPA_RES_FILE
else
    echo
    echo "[Hopa] Error: compile error."
    exit 1
fi
